import { writable } from 'svelte/store';
export const mapConfig = writable({
  "title": "How well do European students perform in science?",
  "subtitle": "Estonia leads the EU with 527 points in PISA 2025. Across the 27 EU countries, the unweighted average score is around 476 points, compared with an OECD average of 482.",
  "colourSchemeClasses": 7,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nAustria,AT,497,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nBelgium,BE,490,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nBulgaria,BG,421,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nCroatia,HR,476,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nCyprus,CY,411,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nCzechia,CZ,490,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nDenmark,DK,478,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nEstonia,EE,527,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nFinland,FI,504,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nFrance,FR,483,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nGermany,DE,486,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nGreece,EL,434,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nHungary,HU,480,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nIreland,IE,500,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nItaly,IT,483,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nLatvia,LV,468,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nLithuania,LT,488,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nLuxembourg,LU,474,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nMalta,MT,453,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nNetherlands,NL,485,false,\"Caution: one or more PISA sampling standards were not met; interpret the estimate with care.\",OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nPoland,PL,495,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nPortugal,PT,482,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nRomania,RO,425,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nSlovakia,SK,475,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nSlovenia,SI,484,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nSpain,ES,477,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nSweden,SE,485,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,",
  "parsedData": [
    {
      "country": "Austria",
      "id": "AT",
      "value": 497,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Belgium",
      "id": "BE",
      "value": 490,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 421,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": 476,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": 411,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 490,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": 478,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 527,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": 504,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 483,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 486,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": 434,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": 480,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": 500,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 483,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 468,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": 488,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": 474,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Malta",
      "id": "MT",
      "value": 453,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": 485,
      "extraInfo": false,
      "text_content": "Caution: one or more PISA sampling standards were not met; interpret the estimate with care.",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": 495,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": 482,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 425,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovakia",
      "id": "SK",
      "value": 475,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": 484,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": 477,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": 485,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "values",
  "datasetUnit": "fullNumbers",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "blue-purple",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": true,
  "scaleBarAvailable": true,
  "overrideScaleValues": true,
  "legendAvailable": true,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "OECD (2026)",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "PISA measures how well 15-year-old students can apply their knowledge and skills to real-life challenges. In science, the OECD average stood at 482 points in 2025, three points lower than in 2022 and seven points below its 2015 level. Estonia recorded the highest score among EU countries with 527 points, while Cyprus had the lowest at 411. The EU figure of 476 points is an unweighted average calculated from the mean scores of the 27 EU Member States and is not an official OECD EU average.",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "colorBarFirstValue": "400",
  "colorBarLastValue": "530",
  "customUnitLabelAvailable": false,
  "customUnitLabel": "",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "How well do European students perform in science?",
    "subtitle": "Estonia leads the EU with 527 points in PISA 2025. Across the 27 EU countries, the unweighted average score is around 476 points, compared with an OECD average of 482.",
    "textNoteDescription": "Note",
    "textNote": "PISA measures how well 15-year-old students can apply their knowledge and skills to real-life challenges. In science, the OECD average stood at 482 points in 2025, three points lower than in 2022 and seven points below its 2015 level. Estonia recorded the highest score among EU countries with 527 points, while Cyprus had the lowest at 411. The EU figure of 476 points is an unweighted average calculated from the mean scores of the 27 EU Member States and is not an official OECD EU average.",
    "textSourceDescription": "Source",
    "textSource": "OECD (2026)",
    "linkDataAccessDescription": "Access the data",
    "legend1": "No data available",
    "tooltipExtraInfoLabel": "Click here",
    "extraInfo_NL": "Caution: one or more PISA sampling standards were not met; interpret the estimate with care."
  },
  "clusters": [],
  "colorScale": null,
  "extraInfo_NL": "Caution: one or more PISA sampling standards were not met; interpret the estimate with care."
});